export const PERMISSIONS = {
  // Auth
  AUTH_MANAGE: 'auth:manage',

  // Users
  USERS_READ: 'users:read',
  USERS_CREATE: 'users:create',
  USERS_UPDATE: 'users:update',
  USERS_DELETE: 'users:delete',

  // Organizations
  ORGS_READ: 'organizations:read',
  ORGS_CREATE: 'organizations:create',
  ORGS_UPDATE: 'organizations:update',

  // Masters
  MASTERS_READ: 'masters:read',
  MASTERS_MANAGE: 'masters:manage',

  // Industry
  INDUSTRY_READ: 'industry:read',
  INDUSTRY_MANAGE: 'industry:manage',

  // Companies
  COMPANIES_READ: 'companies:read',
  COMPANIES_CREATE: 'companies:create',
  COMPANIES_UPDATE: 'companies:update',
  COMPANIES_DELETE: 'companies:delete',

  // Documents
  DOCUMENTS_READ: 'documents:read',
  DOCUMENTS_UPLOAD: 'documents:upload',
  DOCUMENTS_VERIFY: 'documents:verify',

  // Financial
  FINANCIAL_READ: 'financial:read',
  FINANCIAL_MANAGE: 'financial:manage',

  // CHS
  CHS_READ: 'chs:read',
  CHS_SCORE: 'chs:score',
  CHS_OVERRIDE: 'chs:override',
  CHS_APPROVE: 'chs:approve',

  // Risk
  RISK_READ: 'risk:read',
  RISK_MANAGE: 'risk:manage',

  // Workflow
  WORKFLOW_READ: 'workflow:read',
  WORKFLOW_ACTION: 'workflow:action',

  // Committee
  COMMITTEE_READ: 'committee:read',
  COMMITTEE_VOTE: 'committee:vote',
  COMMITTEE_MANAGE: 'committee:manage',

  // Deals
  DEALS_READ: 'deals:read',
  DEALS_CREATE: 'deals:create',
  DEALS_MANAGE: 'deals:manage',

  // Rails
  DEBT_RAIL_READ: 'debt_rail:read',
  DEBT_RAIL_MANAGE: 'debt_rail:manage',
  EQUITY_RAIL_READ: 'equity_rail:read',
  EQUITY_RAIL_MANAGE: 'equity_rail:manage',
  STARTUP_RAIL_READ: 'startup_rail:read',
  STARTUP_RAIL_MANAGE: 'startup_rail:manage',

  // Reports
  REPORTS_READ: 'reports:read',
  REPORTS_GENERATE: 'reports:generate',
  REPORTS_EXPORT: 'reports:export',

  // Audit
  AUDIT_READ: 'audit:read',

  // Admin
  ADMIN_FULL: 'admin:full',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),

  COMPANY_ADMIN: [
    PERMISSIONS.COMPANIES_READ,
    PERMISSIONS.COMPANIES_UPDATE,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.DOCUMENTS_UPLOAD,
    PERMISSIONS.FINANCIAL_READ,
    PERMISSIONS.FINANCIAL_MANAGE,
    PERMISSIONS.CHS_READ,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.WORKFLOW_ACTION,
    PERMISSIONS.DEALS_READ,
    PERMISSIONS.REPORTS_READ,
  ],

  ANALYST: [
    PERMISSIONS.COMPANIES_READ,
    PERMISSIONS.COMPANIES_UPDATE,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.DOCUMENTS_VERIFY,
    PERMISSIONS.FINANCIAL_READ,
    PERMISSIONS.FINANCIAL_MANAGE,
    PERMISSIONS.CHS_READ,
    PERMISSIONS.CHS_SCORE,
    PERMISSIONS.CHS_OVERRIDE,
    PERMISSIONS.RISK_READ,
    PERMISSIONS.RISK_MANAGE,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.WORKFLOW_ACTION,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_GENERATE,
  ],

  SENIOR_ANALYST: [
    PERMISSIONS.COMPANIES_READ,
    PERMISSIONS.COMPANIES_UPDATE,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.DOCUMENTS_VERIFY,
    PERMISSIONS.FINANCIAL_READ,
    PERMISSIONS.FINANCIAL_MANAGE,
    PERMISSIONS.CHS_READ,
    PERMISSIONS.CHS_SCORE,
    PERMISSIONS.CHS_OVERRIDE,
    PERMISSIONS.CHS_APPROVE,
    PERMISSIONS.RISK_READ,
    PERMISSIONS.RISK_MANAGE,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.WORKFLOW_ACTION,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.REPORTS_EXPORT,
  ],

  LENDER: [
    PERMISSIONS.COMPANIES_READ,
    PERMISSIONS.CHS_READ,
    PERMISSIONS.RISK_READ,
    PERMISSIONS.DEALS_READ,
    PERMISSIONS.DEALS_MANAGE,
    PERMISSIONS.DEBT_RAIL_READ,
    PERMISSIONS.DEBT_RAIL_MANAGE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
  ],

  INVESTOR: [
    PERMISSIONS.COMPANIES_READ,
    PERMISSIONS.CHS_READ,
    PERMISSIONS.RISK_READ,
    PERMISSIONS.DEALS_READ,
    PERMISSIONS.DEALS_MANAGE,
    PERMISSIONS.EQUITY_RAIL_READ,
    PERMISSIONS.EQUITY_RAIL_MANAGE,
    PERMISSIONS.STARTUP_RAIL_READ,
    PERMISSIONS.STARTUP_RAIL_MANAGE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
  ],

  COMMITTEE_MEMBER: [
    PERMISSIONS.COMPANIES_READ,
    PERMISSIONS.CHS_READ,
    PERMISSIONS.RISK_READ,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.COMMITTEE_READ,
    PERMISSIONS.COMMITTEE_VOTE,
    PERMISSIONS.REPORTS_READ,
  ],

  COMMITTEE_CHAIR: [
    PERMISSIONS.COMPANIES_READ,
    PERMISSIONS.CHS_READ,
    PERMISSIONS.RISK_READ,
    PERMISSIONS.WORKFLOW_READ,
    PERMISSIONS.WORKFLOW_ACTION,
    PERMISSIONS.COMMITTEE_READ,
    PERMISSIONS.COMMITTEE_VOTE,
    PERMISSIONS.COMMITTEE_MANAGE,
    PERMISSIONS.CHS_APPROVE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_GENERATE,
  ],
};
